project:
  type: website

website:
  title: "my-brawlstars"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - gamemode.qmd
      - currencies.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



execute:
  freeze: auto